name: Build and test
on: [pull_request, workflow_call]

jobs:
  tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest"]
        version: [21, 25]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.version}}
          distribution: 'temurin'
          architecture: x64
      - name: Build with maven
        run: mvn clean install
